### ISSUE TITLE
License copyright name and year

### ISSUE THREAD

**Issue by xyntechx** [huseinzol05/malay-dataset#11]
Salam :) Saya ingin menggunakan `malay-text.txt` dalam projek saya sendiri. Oleh kerana repository ini menggunakan license Apache 2.0, saya mengerti bahawa license yang original harus diletakkan di dalam folder di mana saya akan gunakan fail tersebut di dalam project saya pun. Namun, saya lihat bahawa license anda tidak lengkap dengan nama dan tahun (dan mungkin item-item lainnya). Adakah anda boleh isikan license di dalam repository ini supaya saya boleh gunakan fail yang telah anda bina dengan benar? Terima kasih!

**Comment by huseinzol05** [comment]
dataset yang mana ye, share link di sini.

**Comment by xyntechx** [comment]
https://github.com/huseinzol05/malay-dataset/blob/master/dictionary/malay-text.txt

**Comment by huseinzol05** [comment]
```bibtex
@misc{Malay-Dataset, We gather Bahasa Malaysia corpus!,
  author = {Husein, Zolkepli},
  title = {Malay-Dataset},
  year = {2018},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/huseinzol05/malay-dataset/blob/master/dictionary/malay-text.txt}}
}
```

But might want to look at DBP dataset, https://github.com/huseinzol05/malay-dataset/tree/master/dictionary/dbp

**Comment by xyntechx** [comment]
Oh okok! Is the DBP dataset more complete? Also, I saw the commit message says "added syllable and more dbp dataset"... does that mean the jupyter notebooks are able to decompose each word into their syllables?

**Comment by huseinzol05** [comment]
not all words from DBP got syllable, https://github.com/huseinzol05/malay-dataset/blob/master/tokenization/syllable/prepare-syllable.ipynb

**Comment by xyntechx** [comment]
Is it because they only have one syllable (e.g. bab) or is it because they're not valid words?

**Comment by huseinzol05** [comment]
im not sure, that one u might want to ask DBP itself.

ayam got, https://prpm.dbp.gov.my/cari1?keyword=ayam
menteri no syllable, https://prpm.dbp.gov.my/cari1?keyword=menteri

**Comment by xyntechx** [comment]
Okay noted! But the two datasets I circled in the above image are complete, right? As in, no valid words in the dictionary have been left out?

**Comment by huseinzol05** [comment]
yep!

**Comment by xyntechx** [comment]
Alright! I'll cite your work accordingly. Thank you so much for your help!
