### ISSUE TITLE
Twitter emotion json data-set not reachable

### ISSUE THREAD

**Issue by exopas95** [huseinzol05/Malay-Dataset#4]
Hi and thanks for all your effort for the data-set
I'm trying to use twitter emotion data-set which but access is getting denied.
Are you aware of this issue? 

Data-set [link](https://malaya-dataset.s3-ap-southeast-1.amazonaws.com/emotion/emotion-twitter-lexicon.json)

**Comment by huseinzol05** [comment]
Done make it public!
