### ISSUE TITLE
Bahasa speech data is not accessible

### ISSUE THREAD

**Issue by smartnose** [huseinzol05/Malay-Dataset#5]
Hello,

Thanks for publishing the speech datasets. One of the link is dead:  https://s3-ap-southeast-1.amazonaws.com/malaya-dataset/speech-bahasa.zip

It's referred here: https://github.com/huseinzol05/Malay-Dataset/tree/master/speech/sebut-perkataan

**Comment by huseinzol05** [comment]
Fixed! https://github.com/huseinzol05/Malay-Dataset/tree/master/speech/sebut-perkataan
