### ISSUE TITLE
Translated SQuAD v2.0 format

### ISSUE THREAD

**Issue by waterhall** [huseinzol05/malay-dataset#6]
Hi, thanks for the dataset. I'm looking at the SQuAD v2.0 dataset and I am a little confused.

The json files are not formatted the same way as in the official SQuAD v2.0 dataset. Would you by any chance have a copy that's formatted in the same way? (same dict structure, same dict keys, correct answer_start etc.)

If not, may I find out more about how the dataset is currently formatted? I see a lot of "<>" and "| |". 
Are the Malay parts presented like this:
Context <> Question || Answer || Answer <> Question || Answer || Answer || Answer <> Question || <> Question ||

So the <> separates context and QA examples, while the || separates the different parts within the QA example?

May I know how this dataset was obtained? Can I assume the answer will definitely be found in the context?

For the English parts included in the dataset, am I correct to assume the answer_start cannot be used, and I have to manually process the Malay part to find the correct answer_start?

Thank you!

**Comment by huseinzol05** [comment]
That one deprecated, latest one, https://github.com/huseinzol05/malay-dataset/tree/master/question-answer/squad

**Comment by waterhall** [comment]
Thank you :)
